before_install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
    - sudo dpkg -i hugo_0.55.6_Linux-64bit.deb

install: skip

script:
    - find . -name '*.toml' | xargs ./.bin/tomlv && hugo
